### ISSUE TITLE
[FEATURE] Add YAML format to the output formats

### ISSUE THREAD

**Issue by guibranco** [guibranco/BancosBrasileiros-MergeTool#156]
**Description:**
Request support for a new output format—YAML—for the data generated by this tool. The currently supported formats are CSV, XML, JSON, and Markdown. The YAML output should follow the same structure as the JSON output.

**Current Output Formats:**
- CSV
- XML
- JSON
- Markdown

**Proposed Output Format:**
- YAML (`bancos.yml`)

**Sample data (in JSON, list of ittems):**
```json
[
  {
    "COMPE": "001",
    "ISPB": "00000000",
    "Document": "00.000.000/0001-91",
    "LongName": "Banco do Brasil S.A.",
    "ShortName": "BCO DO BRASIL S.A.",
    "Network": "RSFN",
    "Type": "Banco Múltiplo",
    "PixType": "DRCT",
    "Charge": true,
    "CreditDocument": true,
    "LegalCheque": true,
    "DetectaFlow": false,
    "PCR": true,
    "PCRP": true,
    "SalaryPortability": "Banco folha e Destinatário",
    "Products": [
      "Capital de Giro",
      "Cheque Especial",
      "Consignado",
      "Imobiliário",
      "Outros Créditos",
      "Pessoal",
      "Troca de Modalidade",
      "Veículos"
    ],
    "Url": "https://www.bb.com.br",
    "DateOperationStarted": "2002-04-22",
    "DatePixStarted": "2020-11-03 06:30:00",
    "DateRegistered": "2021-05-05T09:11:12.7109988-03:00",
    "DateUpdated": "2024-05-15T16:49:45.7277793+00:00"
  },
  {
    "COMPE": "002",
    "ISPB": "11111111",
    "Document": "11.111.111/1111-11",
    "LongName": "Banco Exemplo S.A.",
    "ShortName": "BCO EXEMPLO S.A.",
    "Network": "RSFN",
    "Type": "Banco Digital",
    "PixType": "DRCT",
    "Charge": true,
    "CreditDocument": false,
    "LegalCheque": false,
    "DetectaFlow": true,
    "PCR": false,
    "PCRP": false,
    "SalaryPortability": "Destinatário",
    "Products": [
      "Consignado",
      "Imobiliário",
      "Veículos"
    ],
    "Url": "https://www.bancoexemplo.com.br",
    "DateOperationStarted": "2010-09-15",
    "DatePixStarted": "2021-10-01 09:00:00",
    "DateRegistered": "2021-12-01T12:45:30.1234567-03:00",
    "DateUpdated": "2024-05-20T14:30:25.9999999+00:00"
  }
]
```

**Sample data (in YAML, list of items):**
```yaml
- COMPE: "001"
  ISPB: "00000000"
  Document: "00.000.000/0001-91"
  LongName: "Banco do Brasil S.A."
  ShortName: "BCO DO BRASIL S.A."
  Network: "RSFN"
  Type: "Banco Múltiplo"
  PixType: "DRCT"
  Charge: true
  CreditDocument: true
  LegalCheque: true
  DetectaFlow: false
  PCR: true
  PCRP: true
  SalaryPortability: "Banco folha e Destinatário"
  Products:
    - "Capital de Giro"
    - "Cheque Especial"
    - "Consignado"
    - "Imobiliário"
    - "Outros Créditos"
    - "Pessoal"
    - "Troca de Modalidade"
    - "Veículos"
  Url: "https://www.bb.com.br"
  DateOperationStarted: "2002-04-22"
  DatePixStarted: "2020-11-03 06:30:00"
  DateRegistered: "2021-05-05T09:11:12.7109988-03:00"
  DateUpdated: "2024-05-15T16:49:45.7277793+00:00"

- COMPE: "002"
  ISPB: "11111111"
  Document: "11.111.111/1111-11"
  LongName: "Banco Exemplo S.A."
  ShortName: "BCO EXEMPLO S.A."
  Network: "RSFN"
  Type: "Banco Digital"
  PixType: "DRCT"
  Charge: true
  CreditDocument: false
  LegalCheque: false
  DetectaFlow: true
  PCR: false
  PCRP: false
  SalaryPortability: "Destinatário"
  Products:
    - "Consignado"
    - "Imobiliário"
    - "Veículos"
  Url: "https://www.bancoexemplo.com.br"
  DateOperationStarted: "2010-09-15"
  DatePixStarted: "2021-10-01 09:00:00"
  DateRegistered: "2021-12-01T12:45:30.1234567-03:00"
  DateUpdated: "2024-05-20T14:30:25.9999999+00:00"
```

**Benefits:**
- Provides a human-readable, whitespace-sensitive format.
- Increases compatibility with tools and configurations that prefer YAML.
